Added a filter for specifying the variable to proof
Kryha/zk-states pull request #18
Opened 2023-08-16 14:49 UTC by Mautjee

2023-08-16 14:57 UTC, silimarius requested changes

2023-08-16 14:57 UTC, silimarius commented on src/hooks.ts
> +  console.log("payload", {payload});
delete log

2023-08-16 15:02 UTC, ecovirtual approved these changes

2023-08-17 07:37 UTC, silimarius requested changes
Bump up the lib version in package.json to 0.0.15

2023-08-17 07:45 UTC, silimarius approved these changes

2023-08-17 08:30 UTC, merged